abator(an).
abator(ld).
abator(lm).
abator(nd).
abator(ngan).
abator(nguyen).
abator(nm).
abator(td).
abator(thao).
abator(tm).
abjurer(an).
abjurer(ld).
abjurer(lm).
abjurer(nd).
abjurer(ngan).
abjurer(nguyen).
abjurer(nm).
abjurer(td).
abjurer(thao).
abjurer(tm).
abomination(an).
abomination(ld).
abomination(lm).
abomination(nd).
abomination(ngan).
abomination(nguyen).
abomination(nm).
abomination(td).
abomination(thao).
abomination(tm).
abstainer(an).
abstainer(ld).
abstainer(lm).
abstainer(nd).
abstainer(ngan).
abstainer(nguyen).
abstainer(nm).
abstainer(td).
abstainer(thao).
abstainer(tm).
achiever(an).
achiever(ld).
achiever(lm).
achiever(nd).
achiever(ngan).
achiever(nguyen).
achiever(nm).
achiever(td).
achiever(thao).
achiever(tm).
acquaintance(an).
acquaintance(ld).
acquaintance(lm).
acquaintance(nd).
acquaintance(ngan).
acquaintance(nguyen).
acquaintance(nm).
acquaintance(td).
acquaintance(thao).
acquaintance(tm).
acquirer(an).
acquirer(ld).
acquirer(lm).
acquirer(nd).
acquirer(ngan).
acquirer(nguyen).
acquirer(nm).
acquirer(td).
acquirer(thao).
acquirer(tm).
active(an).
active(ld).
active(lm).
active(nd).
active(ngan).
active(nguyen).
active(nm).
active(td).
active(thao).
active(tm).
actor(an).
actor(ld).
actor(lm).
actor(nd).
actor(ngan).
actor(nguyen).
actor(nm).
actor(td).
actor(thao).
actor(tm).
adjudicator(an).
adjudicator(ld).
adjudicator(lm).
adjudicator(nd).
adjudicator(ngan).
adjudicator(nguyen).
adjudicator(nm).
adjudicator(td).
adjudicator(thao).
adjudicator(tm).
admirer(an).
admirer(ld).
admirer(lm).
admirer(nd).
admirer(ngan).
admirer(nguyen).
admirer(nm).
admirer(td).
admirer(thao).
admirer(tm).
adoptee(an).
adoptee(ld).
adoptee(lm).
adoptee(nd).
adoptee(ngan).
adoptee(nguyen).
adoptee(nm).
adoptee(td).
adoptee(thao).
adoptee(tm).
adore(Y, bh) :- person(Y).
adore(Y, H) :- (Y = ngan ; Y = thao ; Y = nguyen), hometown(Y, H).
adult(an).
adult(ld).
adult(lm).
adult(nd).
adult(ngan).
adult(nguyen).
adult(nm).
adult(td).
adult(thao).
adult(tm).
adventurer(an).
adventurer(ld).
adventurer(lm).
adventurer(nd).
adventurer(ngan).
adventurer(nguyen).
adventurer(nm).
adventurer(td).
adventurer(thao).
adventurer(tm).
adversary(an).
adversary(ld).
adversary(lm).
adversary(nd).
adversary(ngan).
adversary(nguyen).
adversary(nm).
adversary(td).
adversary(thao).
adversary(tm).
advisee(an).
advisee(ld).
advisee(lm).
advisee(nd).
advisee(ngan).
advisee(nguyen).
advisee(nm).
advisee(td).
advisee(thao).
advisee(tm).
advocate(an).
advocate(ld).
advocate(lm).
advocate(nd).
advocate(ngan).
advocate(nguyen).
advocate(nm).
advocate(td).
advocate(thao).
advocate(tm).
affiant(an).
affiant(ld).
affiant(lm).
affiant(nd).
affiant(ngan).
affiant(nguyen).
affiant(nm).
affiant(td).
affiant(thao).
affiant(tm).
african(an).
african(ld).
african(lm).
african(nd).
african(ngan).
african(nguyen).
african(nm).
african(td).
african(thao).
african(tm).
agnostic(an).
agnostic(ld).
agnostic(lm).
agnostic(nd).
agnostic(ngan).
agnostic(nguyen).
agnostic(nm).
agnostic(td).
agnostic(thao).
agnostic(tm).
agriculturist(ld).
agriculturist(lm).
alter_ego(ngan, nguyen).
alter_ego(ngan, thao).
alter_ego(nguyen, ngan).
alter_ego(nguyen, thao).
alter_ego(thao, ngan).
alter_ego(thao, nguyen).
amateur(an).
amateur(ld).
amateur(lm).
amateur(nd).
amateur(ngan).
amateur(nguyen).
amateur(nm).
amateur(td).
amateur(thao).
amateur(tm).
amerindian(an).
amerindian(ld).
amerindian(lm).
amerindian(nd).
amerindian(ngan).
amerindian(nguyen).
amerindian(nm).
amerindian(td).
amerindian(thao).
amerindian(tm).
amigo(ngan, nguyen).
amigo(ngan, thao).
amigo(nguyen, ngan).
amigo(nguyen, thao).
amigo(thao, ngan).
amigo(thao, nguyen).
ancient(an).
ancient(ld).
ancient(lm).
ancient(nd).
ancient(ngan).
ancient(nguyen).
ancient(nm).
ancient(td).
ancient(thao).
ancient(tm).
angler(td).
anomaly(an).
anomaly(ld).
anomaly(lm).
anomaly(nd).
anomaly(ngan).
anomaly(nguyen).
anomaly(nm).
anomaly(td).
anomaly(thao).
anomaly(tm).
anti(an).
anti(ld).
anti(lm).
anti(nd).
anti(ngan).
anti(nguyen).
anti(nm).
anti(td).
anti(thao).
anti(tm).
anti_american(an).
anti_american(ld).
anti_american(lm).
anti_american(nd).
anti_american(ngan).
anti_american(nguyen).
anti_american(nm).
anti_american(td).
anti_american(thao).
anti_american(tm).
applicant(an).
applicant(ld).
applicant(lm).
applicant(nd).
applicant(ngan).
applicant(nguyen).
applicant(nm).
applicant(td).
applicant(thao).
applicant(tm).
appointee(an).
appointee(ld).
appointee(lm).
appointee(nd).
appointee(ngan).
appointee(nguyen).
appointee(nm).
appointee(td).
appointee(thao).
appointee(tm).
appreciator(an).
appreciator(ld).
appreciator(lm).
appreciator(nd).
appreciator(ngan).
appreciator(nguyen).
appreciator(nm).
appreciator(td).
appreciator(thao).
appreciator(tm).
apprehender(an).
apprehender(ld).
apprehender(lm).
apprehender(nd).
apprehender(ngan).
apprehender(nguyen).
apprehender(nm).
apprehender(td).
apprehender(thao).
apprehender(tm).
aquarius(an).
aquarius(ld).
aquarius(lm).
aquarius(nd).
aquarius(ngan).
aquarius(nguyen).
aquarius(nm).
aquarius(td).
aquarius(thao).
aquarius(tm).
archaist(an).
archaist(ld).
archaist(lm).
archaist(nd).
archaist(ngan).
archaist(nguyen).
archaist(nm).
archaist(td).
archaist(thao).
archaist(tm).
aries(an).
aries(ld).
aries(lm).
aries(nd).
aries(ngan).
aries(nguyen).
aries(nm).
aries(td).
aries(thao).
aries(tm).
arrogator(an).
arrogator(ld).
arrogator(lm).
arrogator(nd).
arrogator(ngan).
arrogator(nguyen).
arrogator(nm).
arrogator(td).
arrogator(thao).
arrogator(tm).
art_student(ngan).
art_student(nguyen).
art_student(thao).
assessee(an).
assessee(ld).
assessee(lm).
assessee(nd).
assessee(ngan).
assessee(nguyen).
assessee(nm).
assessee(td).
assessee(thao).
assessee(tm).
asthmatic(an).
asthmatic(ld).
asthmatic(lm).
asthmatic(nd).
asthmatic(ngan).
asthmatic(nguyen).
asthmatic(nm).
asthmatic(td).
asthmatic(thao).
asthmatic(tm).
at(ngan, uit).
at(nguyen, uit).
at(thao, uit).
auditor(ngan).
auditor(nguyen).
auditor(thao).
authority(an).
authority(ld).
authority(lm).
authority(nd).
authority(ngan).
authority(nguyen).
authority(nm).
authority(td).
authority(thao).
authority(tm).
autodidact(an).
autodidact(ld).
autodidact(lm).
autodidact(nd).
autodidact(ngan).
autodidact(nguyen).
autodidact(nm).
autodidact(td).
autodidact(thao).
autodidact(tm).
baby_boomer(an).
baby_boomer(ld).
baby_boomer(lm).
baby_boomer(nd).
baby_boomer(ngan).
baby_boomer(nguyen).
baby_boomer(nm).
baby_boomer(td).
baby_boomer(thao).
baby_boomer(tm).
baby_buster(an).
baby_buster(ld).
baby_buster(lm).
baby_buster(nd).
baby_buster(ngan).
baby_buster(nguyen).
baby_buster(nm).
baby_buster(td).
baby_buster(thao).
baby_buster(tm).
bad_guy(an).
bad_guy(ld).
bad_guy(lm).
bad_guy(nd).
bad_guy(ngan).
bad_guy(nguyen).
bad_guy(nm).
bad_guy(td).
bad_guy(thao).
bad_guy(tm).
bad_person(an).
bad_person(ld).
bad_person(lm).
bad_person(nd).
bad_person(ngan).
bad_person(nguyen).
bad_person(nm).
bad_person(td).
bad_person(thao).
bad_person(tm).
baldhead(an).
baldhead(ld).
baldhead(lm).
baldhead(nd).
baldhead(ngan).
baldhead(nguyen).
baldhead(nm).
baldhead(td).
baldhead(thao).
baldhead(tm).
balker(an).
balker(ld).
balker(lm).
balker(nd).
balker(ngan).
balker(nguyen).
balker(nm).
balker(td).
balker(thao).
balker(tm).
bather(an).
bather(ld).
bather(lm).
bather(nd).
bather(ngan).
bather(nguyen).
bather(nm).
bather(td).
bather(thao).
bather(tm).
be_born(ngan, vt).
be_born(nguyen, gl).
be_born(thao, vt).
beach(bh).
beard(an).
beard(ld).
beard(lm).
beard(nd).
beard(ngan).
beard(nguyen).
beard(nm).
beard(td).
beard(thao).
beard(tm).
beautiful(bh).
bedfellow(an).
bedfellow(ld).
bedfellow(lm).
bedfellow(nd).
bedfellow(ngan).
bedfellow(nguyen).
bedfellow(nm).
bedfellow(td).
bedfellow(thao).
bedfellow(tm).
beekeeper(ld).
beekeeper(lm).
bereaved(an).
bereaved(ld).
bereaved(lm).
bereaved(nd).
bereaved(ngan).
bereaved(nguyen).
bereaved(nm).
bereaved(td).
bereaved(thao).
bereaved(tm).
best(an).
best(ld).
best(lm).
best(nd).
best(ngan).
best(nguyen).
best(nm).
best(td).
best(thao).
best(tm).
best_friend(ngan, nguyen).
best_friend(ngan, thao).
best_friend(nguyen, ngan).
best_friend(nguyen, thao).
best_friend(thao, ngan).
best_friend(thao, nguyen).
birth(an).
birth(ld).
birth(lm).
birth(nd).
birth(ngan).
birth(nguyen).
birth(nm).
birth(td).
birth(thao).
birth(tm).
biter(an).
biter(ld).
biter(lm).
biter(nd).
biter(ngan).
biter(nguyen).
biter(nm).
biter(td).
biter(thao).
biter(tm).
black(an).
black(ld).
black(lm).
black(nd).
black(ngan).
black(nguyen).
black(nm).
black(td).
black(thao).
black(tm).
blogger(an).
blogger(ld).
blogger(lm).
blogger(nd).
blogger(ngan).
blogger(nguyen).
blogger(nm).
blogger(td).
blogger(thao).
blogger(tm).
blond(an).
blond(ld).
blond(lm).
blond(nd).
blond(ngan).
blond(nguyen).
blond(nm).
blond(td).
blond(thao).
blond(tm).
bluecoat(an).
bluecoat(ld).
bluecoat(lm).
bluecoat(nd).
bluecoat(ngan).
bluecoat(nguyen).
bluecoat(nm).
bluecoat(td).
bluecoat(thao).
bluecoat(tm).
bodybuilder(an).
bodybuilder(ld).
bodybuilder(lm).
bodybuilder(nd).
bodybuilder(ngan).
bodybuilder(nguyen).
bodybuilder(nm).
bodybuilder(td).
bodybuilder(thao).
bodybuilder(tm).
bomber(an).
bomber(ld).
bomber(lm).
bomber(nd).
bomber(ngan).
bomber(nguyen).
bomber(nm).
bomber(td).
bomber(thao).
bomber(tm).
bracing(bh).
brisk(bh).
brother(ngan, nguyen).
brother(ngan, thao).
brother(nguyen, ngan).
brother(nguyen, thao).
brother(thao, ngan).
brother(thao, nguyen).
brunet(an).
brunet(ld).
brunet(lm).
brunet(nd).
brunet(ngan).
brunet(nguyen).
brunet(nm).
brunet(td).
brunet(thao).
brunet(tm).
buddy(ngan, nguyen).
buddy(ngan, thao).
buddy(nguyen, ngan).
buddy(nguyen, thao).
buddy(thao, ngan).
buddy(thao, nguyen).
bullfighter(an).
bullfighter(ld).
bullfighter(lm).
bullfighter(nd).
bullfighter(ngan).
bullfighter(nguyen).
bullfighter(nm).
bullfighter(td).
bullfighter(thao).
bullfighter(tm).
buster(an).
buster(ld).
buster(lm).
buster(nd).
buster(ngan).
buster(nguyen).
buster(nm).
buster(td).
buster(thao).
buster(tm).
cancer(an).
cancer(ld).
cancer(lm).
cancer(nd).
cancer(ngan).
cancer(nguyen).
cancer(nm).
cancer(td).
cancer(thao).
cancer(tm).
candidate(an).
candidate(ld).
candidate(lm).
candidate(nd).
candidate(ngan).
candidate(nguyen).
candidate(nm).
candidate(td).
candidate(thao).
candidate(tm).
capitalist(an).
capitalist(ld).
capitalist(lm).
capitalist(nd).
capitalist(ngan).
capitalist(nguyen).
capitalist(nm).
capitalist(td).
capitalist(thao).
capitalist(tm).
capricorn(an).
capricorn(ld).
capricorn(lm).
capricorn(nd).
capricorn(ngan).
capricorn(nguyen).
capricorn(nm).
capricorn(td).
capricorn(thao).
capricorn(tm).
captor(an).
captor(ld).
captor(lm).
captor(nd).
captor(ngan).
captor(nguyen).
captor(nm).
captor(td).
captor(thao).
captor(tm).
care_for(Y, bh) :- person(Y).
care_for(Y, H) :- (Y = ngan ; Y = thao ; Y = nguyen), hometown(Y, H).
case(an).
case(ld).
case(lm).
case(nd).
case(ngan).
case(nguyen).
case(nm).
case(td).
case(thao).
case(tm).
cashier(an).
cashier(ld).
cashier(lm).
cashier(nd).
cashier(ngan).
cashier(nguyen).
cashier(nm).
cashier(td).
cashier(thao).
cashier(tm).
catechumen(ngan).
catechumen(nguyen).
catechumen(thao).
causal_agent(an).
causal_agent(ld).
causal_agent(lm).
causal_agent(nd).
causal_agent(ngan).
causal_agent(nguyen).
causal_agent(nm).
causal_agent(td).
causal_agent(thao).
causal_agent(tm).
celebrant(an).
celebrant(ld).
celebrant(lm).
celebrant(nd).
celebrant(ngan).
celebrant(nguyen).
celebrant(nm).
celebrant(td).
celebrant(thao).
celebrant(tm).
censor(an).
censor(ld).
censor(lm).
censor(nd).
censor(ngan).
censor(nguyen).
censor(nm).
censor(td).
censor(thao).
censor(tm).
chameleon(an).
chameleon(ld).
chameleon(lm).
chameleon(nd).
chameleon(ngan).
chameleon(nguyen).
chameleon(nm).
chameleon(td).
chameleon(thao).
chameleon(tm).
changer(an).
changer(ld).
changer(lm).
changer(nd).
changer(ngan).
changer(nguyen).
changer(nm).
changer(td).
changer(thao).
changer(tm).
charmer(an).
charmer(ld).
charmer(lm).
charmer(nd).
charmer(ngan).
charmer(nguyen).
charmer(nm).
charmer(td).
charmer(thao).
charmer(tm).
child(an).
child(ld).
child(lm).
child(nd).
child(ngan).
child(nguyen).
child(nm).
child(td).
child(thao).
child(tm).
chutzpanik(an).
chutzpanik(ld).
chutzpanik(lm).
chutzpanik(nd).
chutzpanik(ngan).
chutzpanik(nguyen).
chutzpanik(nm).
chutzpanik(td).
chutzpanik(thao).
chutzpanik(tm).
city(gl).
city(vt).
closer(an).
closer(ld).
closer(lm).
closer(nd).
closer(ngan).
closer(nguyen).
closer(nm).
closer(td).
closer(thao).
closer(tm).
clumsy_person(an).
clumsy_person(ld).
clumsy_person(lm).
clumsy_person(nd).
clumsy_person(ngan).
clumsy_person(nguyen).
clumsy_person(nm).
clumsy_person(td).
clumsy_person(thao).
clumsy_person(tm).
coastal(vt).
collector(an).
collector(ld).
collector(lm).
collector(nd).
collector(ngan).
collector(nguyen).
collector(nm).
collector(td).
collector(thao).
collector(tm).
collegian(ngan).
collegian(nguyen).
collegian(thao).
color_blind_person(an).
color_blind_person(ld).
color_blind_person(lm).
color_blind_person(nd).
color_blind_person(ngan).
color_blind_person(nguyen).
color_blind_person(nm).
color_blind_person(td).
color_blind_person(thao).
color_blind_person(tm).
combatant(an).
combatant(ld).
combatant(lm).
combatant(nd).
combatant(ngan).
combatant(nguyen).
combatant(nm).
combatant(td).
combatant(thao).
combatant(tm).
commoner(an).
commoner(ld).
commoner(lm).
commoner(nd).
commoner(ngan).
commoner(nguyen).
commoner(nm).
commoner(td).
commoner(thao).
commoner(tm).
communicator(an).
communicator(ld).
communicator(lm).
communicator(nd).
communicator(ngan).
communicator(nguyen).
communicator(nm).
communicator(td).
communicator(thao).
communicator(tm).
companion(ngan, nguyen).
companion(ngan, thao).
companion(nguyen, ngan).
companion(nguyen, thao).
companion(thao, ngan).
companion(thao, nguyen).
complexifier(an).
complexifier(ld).
complexifier(lm).
complexifier(nd).
complexifier(ngan).
complexifier(nguyen).
complexifier(nm).
complexifier(td).
complexifier(thao).
complexifier(tm).
compulsive(an).
compulsive(ld).
compulsive(lm).
compulsive(nd).
compulsive(ngan).
compulsive(nguyen).
compulsive(nm).
compulsive(td).
compulsive(thao).
compulsive(tm).
computer_user(an).
computer_user(ld).
computer_user(lm).
computer_user(nd).
computer_user(ngan).
computer_user(nguyen).
computer_user(nm).
computer_user(td).
computer_user(thao).
computer_user(tm).
confidant(ngan, nguyen).
confidant(ngan, thao).
confidant(nguyen, ngan).
confidant(nguyen, thao).
confidant(thao, ngan).
confidant(thao, nguyen).
contadino(ld).
contadino(lm).
contemplative(an).
contemplative(ld).
contemplative(lm).
contemplative(nd).
contemplative(ngan).
contemplative(nguyen).
contemplative(nm).
contemplative(td).
contemplative(thao).
contemplative(tm).
contestant(an).
contestant(ld).
contestant(lm).
contestant(nd).
contestant(ngan).
contestant(nguyen).
contestant(nm).
contestant(td).
contestant(thao).
contestant(tm).
convert(an).
convert(ld).
convert(lm).
convert(nd).
convert(ngan).
convert(nguyen).
convert(nm).
convert(td).
convert(thao).
convert(tm).
copycat(an).
copycat(ld).
copycat(lm).
copycat(nd).
copycat(ngan).
copycat(nguyen).
copycat(nm).
copycat(td).
copycat(thao).
copycat(tm).
counter(an).
counter(ld).
counter(lm).
counter(nd).
counter(ngan).
counter(nguyen).
counter(nm).
counter(td).
counter(thao).
counter(tm).
counterterrorist(an).
counterterrorist(ld).
counterterrorist(lm).
counterterrorist(nd).
counterterrorist(ngan).
counterterrorist(nguyen).
counterterrorist(nm).
counterterrorist(td).
counterterrorist(thao).
counterterrorist(tm).
coward(an).
coward(ld).
coward(lm).
coward(nd).
coward(ngan).
coward(nguyen).
coward(nm).
coward(td).
coward(thao).
coward(tm).
crammer(ngan).
crammer(nguyen).
crammer(thao).
crawler(an).
crawler(ld).
crawler(lm).
crawler(nd).
crawler(ngan).
crawler(nguyen).
crawler(nm).
crawler(td).
crawler(thao).
crawler(tm).
creator(an).
creator(ld).
creator(lm).
creator(nd).
creator(ngan).
creator(nguyen).
creator(nm).
creator(td).
creator(thao).
creator(tm).
creature(an).
creature(ld).
creature(lm).
creature(nd).
creature(ngan).
creature(nguyen).
creature(nm).
creature(td).
creature(thao).
creature(tm).
creditor(an).
creditor(ld).
creditor(lm).
creditor(nd).
creditor(ngan).
creditor(nguyen).
creditor(nm).
creditor(td).
creditor(thao).
creditor(tm).
cripple(an).
cripple(ld).
cripple(lm).
cripple(nd).
cripple(ngan).
cripple(nguyen).
cripple(nm).
cripple(td).
cripple(thao).
cripple(tm).
dad(ld).
dad(nd).
dad(td).
dada(ld).
dada(nd).
dada(td).
daddy(ld).
daddy(nd).
daddy(td).
dairyman(ld).
dairyman(lm).
dancer(an).
dancer(ld).
dancer(lm).
dancer(nd).
dancer(ngan).
dancer(nguyen).
dancer(nm).
dancer(td).
dancer(thao).
dancer(tm).
dead_person(an).
dead_person(ld).
dead_person(lm).
dead_person(nd).
dead_person(ngan).
dead_person(nguyen).
dead_person(nm).
dead_person(td).
dead_person(thao).
dead_person(tm).
deaf_person(an).
deaf_person(ld).
deaf_person(lm).
deaf_person(nd).
deaf_person(ngan).
deaf_person(nguyen).
deaf_person(nm).
deaf_person(td).
deaf_person(thao).
deaf_person(tm).
debaser(an).
debaser(ld).
debaser(lm).
debaser(nd).
debaser(ngan).
debaser(nguyen).
debaser(nm).
debaser(td).
debaser(thao).
debaser(tm).
debtor(an).
debtor(ld).
debtor(lm).
debtor(nd).
debtor(ngan).
debtor(nguyen).
debtor(nm).
debtor(td).
debtor(thao).
debtor(tm).
defecator(an).
defecator(ld).
defecator(lm).
defecator(nd).
defecator(ngan).
defecator(nguyen).
defecator(nm).
defecator(td).
defecator(thao).
defecator(tm).
delayer(an).
delayer(ld).
delayer(lm).
delayer(nd).
delayer(ngan).
delayer(nguyen).
delayer(nm).
delayer(td).
delayer(thao).
delayer(tm).
deliverer(an).
deliverer(ld).
deliverer(lm).
deliverer(nd).
deliverer(ngan).
deliverer(nguyen).
deliverer(nm).
deliverer(td).
deliverer(thao).
deliverer(tm).
demander(an).
demander(ld).
demander(lm).
demander(nd).
demander(ngan).
demander(nguyen).
demander(nm).
demander(td).
demander(thao).
demander(tm).
dieter(an).
dieter(ld).
dieter(lm).
dieter(nd).
dieter(ngan).
dieter(nguyen).
dieter(nm).
dieter(td).
dieter(thao).
dieter(tm).
differentiator(an).
differentiator(ld).
differentiator(lm).
differentiator(nd).
differentiator(ngan).
differentiator(nguyen).
differentiator(nm).
differentiator(td).
differentiator(thao).
differentiator(tm).
disentangler(an).
disentangler(ld).
disentangler(lm).
disentangler(nd).
disentangler(ngan).
disentangler(nguyen).
disentangler(nm).
disentangler(td).
disentangler(thao).
disentangler(tm).
disputant(an).
disputant(ld).
disputant(lm).
disputant(nd).
disputant(ngan).
disputant(nguyen).
disputant(nm).
disputant(td).
disputant(thao).
disputant(tm).
dissenter(an).
dissenter(ld).
dissenter(lm).
dissenter(nd).
dissenter(ngan).
dissenter(nguyen).
dissenter(nm).
dissenter(td).
dissenter(thao).
dissenter(tm).
divider(an).
divider(ld).
divider(lm).
divider(nd).
divider(ngan).
divider(nguyen).
divider(nm).
divider(td).
divider(thao).
divider(tm).
domestic_partner(an).
domestic_partner(ld).
domestic_partner(lm).
domestic_partner(nd).
domestic_partner(ngan).
domestic_partner(nguyen).
domestic_partner(nm).
domestic_partner(td).
domestic_partner(thao).
domestic_partner(tm).
dote(Y, bh) :- person(Y).
dote(Y, H) :- (Y = ngan ; Y = thao ; Y = nguyen), hometown(Y, H).
double(an).
double(ld).
double(lm).
double(nd).
double(ngan).
double(nguyen).
double(nm).
double(td).
double(thao).
double(tm).
dresser(an).
dresser(ld).
dresser(lm).
dresser(nd).
dresser(ngan).
dresser(nguyen).
dresser(nm).
dresser(td).
dresser(thao).
dresser(tm).
dribbler(an).
dribbler(ld).
dribbler(lm).
dribbler(nd).
dribbler(ngan).
dribbler(nguyen).
dribbler(nm).
dribbler(td).
dribbler(thao).
dribbler(tm).
drug_user(an).
drug_user(ld).
drug_user(lm).
drug_user(nd).
drug_user(ngan).
drug_user(nguyen).
drug_user(nm).
drug_user(td).
drug_user(thao).
drug_user(tm).
dyslectic(an).
dyslectic(ld).
dyslectic(lm).
dyslectic(nd).
dyslectic(ngan).
dyslectic(nguyen).
dyslectic(nm).
dyslectic(td).
dyslectic(thao).
dyslectic(tm).
ectomorph(an).
ectomorph(ld).
ectomorph(lm).
ectomorph(nd).
ectomorph(ngan).
ectomorph(nguyen).
ectomorph(nm).
ectomorph(td).
ectomorph(thao).
ectomorph(tm).
educatee(ngan).
educatee(nguyen).
educatee(thao).
effecter(an).
effecter(ld).
effecter(lm).
effecter(nd).
effecter(ngan).
effecter(nguyen).
effecter(nm).
effecter(td).
effecter(thao).
effecter(tm).
elizabethan(an).
elizabethan(ld).
elizabethan(lm).
elizabethan(nd).
elizabethan(ngan).
elizabethan(nguyen).
elizabethan(nm).
elizabethan(td).
elizabethan(thao).
elizabethan(tm).
emotional_person(an).
emotional_person(ld).
emotional_person(lm).
emotional_person(nd).
emotional_person(ngan).
emotional_person(nguyen).
emotional_person(nm).
emotional_person(td).
emotional_person(thao).
emotional_person(tm).
endomorph(an).
endomorph(ld).
endomorph(lm).
endomorph(nd).
endomorph(ngan).
endomorph(nguyen).
endomorph(nm).
endomorph(td).
endomorph(thao).
endomorph(tm).
engineer(an).
engineer(ld).
engineer(lm).
engineer(nd).
engineer(ngan).
engineer(nguyen).
engineer(nm).
engineer(td).
engineer(thao).
engineer(tm).
enjoyer(an).
enjoyer(ld).
enjoyer(lm).
enjoyer(nd).
enjoyer(ngan).
enjoyer(nguyen).
enjoyer(nm).
enjoyer(td).
enjoyer(thao).
enjoyer(tm).
enrollee(an).
enrollee(ld).
enrollee(lm).
enrollee(nd).
enrollee(ngan).
enrollee(nguyen).
enrollee(nm).
enrollee(td).
enrollee(thao).
enrollee(tm).
entertainer(an).
entertainer(ld).
entertainer(lm).
entertainer(nd).
entertainer(ngan).
entertainer(nguyen).
entertainer(nm).
entertainer(td).
entertainer(thao).
entertainer(tm).
ethnic(an).
ethnic(ld).
ethnic(lm).
ethnic(nd).
ethnic(ngan).
ethnic(nguyen).
ethnic(nm).
ethnic(td).
ethnic(thao).
ethnic(tm).
etonian(ngan).
etonian(nguyen).
etonian(thao).
experimenter(an).
experimenter(ld).
experimenter(lm).
experimenter(nd).
experimenter(ngan).
experimenter(nguyen).
experimenter(nm).
experimenter(td).
experimenter(thao).
experimenter(tm).
expert(an).
expert(ld).
expert(lm).
expert(nd).
expert(ngan).
expert(nguyen).
expert(nm).
expert(td).
expert(thao).
expert(tm).
explorer(an).
explorer(ld).
explorer(lm).
explorer(nd).
explorer(ngan).
explorer(nguyen).
explorer(nm).
explorer(td).
explorer(thao).
explorer(tm).
extrovert(an).
extrovert(ld).
extrovert(lm).
extrovert(nd).
extrovert(ngan).
extrovert(nguyen).
extrovert(nm).
extrovert(td).
extrovert(thao).
extrovert(tm).
exuberant(gl).
face(an).
face(ld).
face(lm).
face(nd).
face(ngan).
face(nguyen).
face(nm).
face(td).
face(thao).
face(tm).
faddist(an).
faddist(ld).
faddist(lm).
faddist(nd).
faddist(ngan).
faddist(nguyen).
faddist(nm).
faddist(td).
faddist(thao).
faddist(tm).
faller(an).
faller(ld).
faller(lm).
faller(nd).
faller(ngan).
faller(nguyen).
faller(nm).
faller(td).
faller(thao).
faller(tm).
family(ngan, nd).
family(ngan, nm).
family(nguyen, ld).
family(nguyen, lm).
family(thao, td).
family(thao, tm).
farmer(ld).
farmer(lm).
fastener(an).
fastener(ld).
fastener(lm).
fastener(nd).
fastener(ngan).
fastener(nguyen).
fastener(nm).
fastener(td).
fastener(thao).
fastener(tm).
father(ld).
father(nd).
father(td).
female(an).
female(ld).
female(lm).
female(nd).
female(ngan).
female(nguyen).
female(nm).
female(td).
female(thao).
female(tm).
fiduciary(an).
fiduciary(ld).
fiduciary(lm).
fiduciary(nd).
fiduciary(ngan).
fiduciary(nguyen).
fiduciary(nm).
fiduciary(td).
fiduciary(thao).
fiduciary(tm).
first_rater(an).
first_rater(ld).
first_rater(lm).
first_rater(nd).
first_rater(ngan).
first_rater(nguyen).
first_rater(nm).
first_rater(td).
first_rater(thao).
first_rater(tm).
fisher(td).
fisherman(td).
fishmonger(nd).
fishmonger(nm).
fishwife(nd).
fishwife(nm).
flatmate(ngan, nguyen).
flatmate(ngan, thao).
flatmate(nguyen, ngan).
flatmate(nguyen, thao).
flatmate(thao, ngan).
flatmate(thao, nguyen).
follower(an).
follower(ld).
follower(lm).
follower(nd).
follower(ngan).
follower(nguyen).
follower(nm).
follower(td).
follower(thao).
follower(tm).
forester(ld).
forester(lm).
free_agent(an).
free_agent(ld).
free_agent(lm).
free_agent(nd).
free_agent(ngan).
free_agent(nguyen).
free_agent(nm).
free_agent(td).
free_agent(thao).
free_agent(tm).
fresh(bh).
friend(ngan, nguyen).
friend(ngan, thao).
friend(nguyen, ngan).
friend(nguyen, thao).
friend(thao, ngan).
friend(thao, nguyen).
from(ngan, vt).
from(nguyen, gl).
from(thao, vt).
fugitive(an).
fugitive(ld).
fugitive(lm).
fugitive(nd).
fugitive(ngan).
fugitive(nguyen).
fugitive(nm).
fugitive(td).
fugitive(thao).
fugitive(tm).
gainer(an).
gainer(ld).
gainer(lm).
gainer(nd).
gainer(ngan).
gainer(nguyen).
gainer(nm).
gainer(td).
gainer(thao).
gainer(tm).
gambler(an).
gambler(ld).
gambler(lm).
gambler(nd).
gambler(ngan).
gambler(nguyen).
gambler(nm).
gambler(td).
gambler(thao).
gambler(tm).
gatekeeper(an).
gatekeeper(ld).
gatekeeper(lm).
gatekeeper(nd).
gatekeeper(ngan).
gatekeeper(nguyen).
gatekeeper(nm).
gatekeeper(td).
gatekeeper(thao).
gatekeeper(tm).
gatherer(an).
gatherer(ld).
gatherer(lm).
gatherer(nd).
gatherer(ngan).
gatherer(nguyen).
gatherer(nm).
gatherer(td).
gatherer(thao).
gatherer(tm).
gemini(an).
gemini(ld).
gemini(lm).
gemini(nd).
gemini(ngan).
gemini(nguyen).
gemini(nm).
gemini(td).
gemini(thao).
gemini(tm).
gentile(an).
gentile(ld).
gentile(lm).
gentile(nd).
gentile(ngan).
gentile(nguyen).
gentile(nm).
gentile(td).
gentile(thao).
gentile(tm).
geological_formation(bh).
girlfriend(ngan, nguyen).
girlfriend(ngan, thao).
girlfriend(nguyen, ngan).
girlfriend(nguyen, thao).
girlfriend(thao, ngan).
girlfriend(thao, nguyen).
good_guy(an).
good_guy(ld).
good_guy(lm).
good_guy(nd).
good_guy(ngan).
good_guy(nguyen).
good_guy(nm).
good_guy(td).
good_guy(thao).
good_guy(tm).
good_person(an).
good_person(ld).
good_person(lm).
good_person(nd).
good_person(ngan).
good_person(nguyen).
good_person(nm).
good_person(td).
good_person(thao).
good_person(tm).
granger(ld).
granger(lm).
granter(an).
granter(ld).
granter(lm).
granter(nd).
granter(ngan).
granter(nguyen).
granter(nm).
granter(td).
granter(thao).
granter(tm).
greeter(an).
greeter(ld).
greeter(lm).
greeter(nd).
greeter(ngan).
greeter(nguyen).
greeter(nm).
greeter(td).
greeter(thao).
greeter(tm).
grinner(an).
grinner(ld).
grinner(lm).
grinner(nd).
grinner(ngan).
grinner(nguyen).
grinner(nm).
grinner(td).
grinner(thao).
grinner(tm).
groaner(an).
groaner(ld).
groaner(lm).
groaner(nd).
groaner(ngan).
groaner(nguyen).
groaner(nm).
groaner(td).
groaner(thao).
groaner(tm).
grunter(an).
grunter(ld).
grunter(lm).
grunter(nd).
grunter(ngan).
grunter(nguyen).
grunter(nm).
grunter(td).
grunter(thao).
grunter(tm).
guesser(an).
guesser(ld).
guesser(lm).
guesser(nd).
guesser(ngan).
guesser(nguyen).
guesser(nm).
guesser(td).
guesser(thao).
guesser(tm).
handicapped_person(an).
handicapped_person(ld).
handicapped_person(lm).
handicapped_person(nd).
handicapped_person(ngan).
handicapped_person(nguyen).
handicapped_person(nm).
handicapped_person(td).
handicapped_person(thao).
handicapped_person(tm).
hater(an).
hater(ld).
hater(lm).
hater(nd).
hater(ngan).
hater(nguyen).
hater(nm).
hater(td).
hater(thao).
hater(tm).
heterosexual(an).
heterosexual(ld).
heterosexual(lm).
heterosexual(nd).
heterosexual(ngan).
heterosexual(nguyen).
heterosexual(nm).
heterosexual(td).
heterosexual(thao).
heterosexual(tm).
homemaker(tm).
hometown(ngan, vt).
hometown(nguyen, gl).
hometown(thao, vt).
homosexual(an).
homosexual(ld).
homosexual(lm).
homosexual(nd).
homosexual(ngan).
homosexual(nguyen).
homosexual(nm).
homosexual(td).
homosexual(thao).
homosexual(tm).
homunculus(an).
homunculus(ld).
homunculus(lm).
homunculus(nd).
homunculus(ngan).
homunculus(nguyen).
homunculus(nm).
homunculus(td).
homunculus(thao).
homunculus(tm).
hope(an).
hope(ld).
hope(lm).
hope(nd).
hope(ngan).
hope(nguyen).
hope(nm).
hope(td).
hope(thao).
hope(tm).
hoper(an).
hoper(ld).
hoper(lm).
hoper(nd).
hoper(ngan).
hoper(nguyen).
hoper(nm).
hoper(td).
hoper(thao).
hoper(tm).
housewife(tm).
huddler(an).
huddler(ld).
huddler(lm).
huddler(nd).
huddler(ngan).
huddler(nguyen).
huddler(nm).
huddler(td).
huddler(thao).
huddler(tm).
hugger(an).
hugger(ld).
hugger(lm).
hugger(nd).
hugger(ngan).
hugger(nguyen).
hugger(nm).
hugger(td).
hugger(thao).
hugger(tm).
husbandman(ld).
husbandman(lm).
immune(an).
immune(ld).
immune(lm).
immune(nd).
immune(ngan).
immune(nguyen).
immune(nm).
immune(td).
immune(thao).
immune(tm).
in(bh, vt).
in_family(X, F) :- family(X, F).
individual(an).
individual(ld).
individual(lm).
individual(nd).
individual(ngan).
individual(nguyen).
individual(nm).
individual(td).
individual(thao).
individual(tm).
individualist(an).
individualist(ld).
individualist(lm).
individualist(nd).
individualist(ngan).
individualist(nguyen).
individualist(nm).
individualist(td).
individualist(thao).
individualist(tm).
inhabitant(an).
inhabitant(ld).
inhabitant(lm).
inhabitant(nd).
inhabitant(ngan).
inhabitant(nguyen).
inhabitant(nm).
inhabitant(td).
inhabitant(thao).
inhabitant(tm).
innocent(an).
innocent(ld).
innocent(lm).
innocent(nd).
innocent(ngan).
innocent(nguyen).
innocent(nm).
innocent(td).
innocent(thao).
innocent(tm).
insured(an).
insured(ld).
insured(lm).
insured(nd).
insured(ngan).
insured(nguyen).
insured(nm).
insured(td).
insured(thao).
insured(tm).
intellectual(an).
intellectual(ld).
intellectual(lm).
intellectual(nd).
intellectual(ngan).
intellectual(nguyen).
intellectual(nm).
intellectual(td).
intellectual(thao).
intellectual(tm).
interpreter(an).
interpreter(ld).
interpreter(lm).
interpreter(nd).
interpreter(ngan).
interpreter(nguyen).
interpreter(nm).
interpreter(td).
interpreter(thao).
interpreter(tm).
introvert(an).
introvert(ld).
introvert(lm).
introvert(nd).
introvert(ngan).
introvert(nguyen).
introvert(nm).
introvert(td).
introvert(thao).
introvert(tm).
ivy_leaguer(ngan).
ivy_leaguer(nguyen).
ivy_leaguer(thao).
jat(an).
jat(ld).
jat(lm).
jat(nd).
jat(ngan).
jat(nguyen).
jat(nm).
jat(td).
jat(thao).
jat(tm).
jew(an).
jew(ld).
jew(lm).
jew(nd).
jew(ngan).
jew(nguyen).
jew(nm).
jew(td).
jew(thao).
jew(tm).
jewel(an).
jewel(ld).
jewel(lm).
jewel(nd).
jewel(ngan).
jewel(nguyen).
jewel(nm).
jewel(td).
jewel(thao).
jewel(tm).
job(X, agriculturist) :- agriculturist(X).
job(X, angler) :- angler(X).
job(X, beekeeper) :- beekeeper(X).
job(X, contadino) :- contadino(X).
job(X, creator) :- creator(X).
job(X, dairyman) :- dairyman(X).
job(X, farmer) :- farmer(X).
job(X, fisher) :- fisher(X).
job(X, fisherman) :- fisherman(X).
job(X, fishmonger) :- fishmonger(X).
job(X, fishwife) :- fishwife(X).
job(X, forester) :- forester(X).
job(X, granger) :- granger(X).
job(X, homemaker) :- homemaker(X).
job(X, housewife) :- housewife(X).
job(X, husbandman) :- husbandman(X).
job(X, lady_of_the_house) :- lady_of_the_house(X).
job(X, planter) :- planter(X).
job(X, rancher) :- rancher(X).
job(X, skilled_worker) :- skilled_worker(X).
job(X, small_farmer) :- small_farmer(X).
job(X, smallholder) :- smallholder(X).
job(X, sodbuster) :- sodbuster(X).
job(X, sower) :- sower(X).
job(X, stockman) :- stockman(X).
job(X, tenant_farmer) :- tenant_farmer(X).
job(X, tiller) :- tiller(X).
job(X, trader) :- trader(X).
job(X, trawler) :- trawler(X).
job(X, wife) :- wife(X).
job(X, woman_of_the_house) :- woman_of_the_house(X).
jumper(an).
jumper(ld).
jumper(lm).
jumper(nd).
jumper(ngan).
jumper(nguyen).
jumper(nm).
jumper(td).
jumper(thao).
jumper(tm).
junior(an).
junior(ld).
junior(lm).
junior(nd).
junior(ngan).
junior(nguyen).
junior(nm).
junior(td).
junior(thao).
junior(tm).
juvenile(an).
juvenile(ld).
juvenile(lm).
juvenile(nd).
juvenile(ngan).
juvenile(nguyen).
juvenile(nm).
juvenile(td).
juvenile(thao).
juvenile(tm).
killer(an).
killer(ld).
killer(lm).
killer(nd).
killer(ngan).
killer(nguyen).
killer(nm).
killer(td).
killer(thao).
killer(tm).
kink(an).
kink(ld).
kink(lm).
kink(nd).
kink(ngan).
kink(nguyen).
kink(nm).
kink(td).
kink(thao).
kink(tm).
kneeler(an).
kneeler(ld).
kneeler(lm).
kneeler(nd).
kneeler(ngan).
kneeler(nguyen).
kneeler(nm).
kneeler(td).
kneeler(thao).
kneeler(tm).
knocker(an).
knocker(ld).
knocker(lm).
knocker(nd).
knocker(ngan).
knocker(nguyen).
knocker(nm).
knocker(td).
knocker(thao).
knocker(tm).
knower(an).
knower(ld).
knower(lm).
knower(nd).
knower(ngan).
knower(nguyen).
knower(nm).
knower(td).
knower(thao).
knower(tm).
lady_of_the_house(tm).
large_person(an).
large_person(ld).
large_person(lm).
large_person(nd).
large_person(ngan).
large_person(nguyen).
large_person(nm).
large_person(td).
large_person(thao).
large_person(tm).
latin(an).
latin(ld).
latin(lm).
latin(nd).
latin(ngan).
latin(nguyen).
latin(nm).
latin(td).
latin(thao).
latin(tm).
laugher(an).
laugher(ld).
laugher(lm).
laugher(nd).
laugher(ngan).
laugher(nguyen).
laugher(nm).
laugher(td).
laugher(thao).
laugher(tm).
law_student(ngan).
law_student(nguyen).
law_student(thao).
leader(an).
leader(ld).
leader(lm).
leader(nd).
leader(ngan).
leader(nguyen).
leader(nm).
leader(td).
leader(thao).
leader(tm).
learner(an).
learner(ld).
learner(lm).
learner(nd).
learner(ngan).
learner(nguyen).
learner(nm).
learner(td).
learner(thao).
learner(tm).
left_hander(an).
left_hander(ld).
left_hander(lm).
left_hander(nd).
left_hander(ngan).
left_hander(nguyen).
left_hander(nm).
left_hander(td).
left_hander(thao).
left_hander(tm).
leo(an).
leo(ld).
leo(lm).
leo(nd).
leo(ngan).
leo(nguyen).
leo(nm).
leo(td).
leo(thao).
leo(tm).
libra(an).
libra(ld).
libra(lm).
libra(nd).
libra(ngan).
libra(nguyen).
libra(nm).
libra(td).
libra(thao).
libra(tm).
life(an).
life(ld).
life(lm).
life(nd).
life(ngan).
life(nguyen).
life(nm).
life(td).
life(thao).
life(tm).
light(ngan, nguyen).
light(ngan, thao).
light(nguyen, ngan).
light(nguyen, thao).
light(thao, ngan).
light(thao, nguyen).
lightning_rod(an).
lightning_rod(ld).
lightning_rod(lm).
lightning_rod(nd).
lightning_rod(ngan).
lightning_rod(nguyen).
lightning_rod(nm).
lightning_rod(td).
lightning_rod(thao).
lightning_rod(tm).
linguist(an).
linguist(ld).
linguist(lm).
linguist(nd).
linguist(ngan).
linguist(nguyen).
linguist(nm).
linguist(td).
linguist(thao).
linguist(tm).
literate(an).
literate(ld).
literate(lm).
literate(nd).
literate(ngan).
literate(nguyen).
literate(nm).
literate(td).
literate(thao).
literate(tm).
liver(an).
liver(ld).
liver(lm).
liver(nd).
liver(ngan).
liver(nguyen).
liver(nm).
liver(td).
liver(thao).
liver(tm).
longer(an).
longer(ld).
longer(lm).
longer(nd).
longer(ngan).
longer(nguyen).
longer(nm).
longer(td).
longer(thao).
longer(tm).
loose_cannon(an).
loose_cannon(ld).
loose_cannon(lm).
loose_cannon(nd).
loose_cannon(ngan).
loose_cannon(nguyen).
loose_cannon(nm).
loose_cannon(td).
loose_cannon(thao).
loose_cannon(tm).
love(Y, bh) :- person(Y).
love(Y, H) :- (Y = ngan ; Y = thao ; Y = nguyen), hometown(Y, H).
loved_one(an).
loved_one(ld).
loved_one(lm).
loved_one(nd).
loved_one(ngan).
loved_one(nguyen).
loved_one(nm).
loved_one(td).
loved_one(thao).
loved_one(tm).
lover(an).
lover(ld).
lover(lm).
lover(nd).
lover(ngan).
lover(nguyen).
lover(nm).
lover(td).
lover(thao).
lover(tm).
lush(gl).
luxuriant(gl).
ma(lm).
ma(nm).
ma(tm).
machine(an).
machine(ld).
machine(lm).
machine(nd).
machine(ngan).
machine(nguyen).
machine(nm).
machine(td).
machine(thao).
machine(tm).
mailer(an).
mailer(ld).
mailer(lm).
mailer(nd).
mailer(ngan).
mailer(nguyen).
mailer(nm).
mailer(td).
mailer(thao).
mailer(tm).
major(ngan).
major(nguyen).
major(thao).
malcontent(an).
malcontent(ld).
malcontent(lm).
malcontent(nd).
malcontent(ngan).
malcontent(nguyen).
malcontent(nm).
malcontent(td).
malcontent(thao).
malcontent(tm).
male(an).
male(ld).
male(lm).
male(nd).
male(ngan).
male(nguyen).
male(nm).
male(td).
male(thao).
male(tm).
mama(lm).
mama(nm).
mama(tm).
mamma(lm).
mamma(nm).
mamma(tm).
mammy(lm).
mammy(nm).
mammy(tm).
man(an).
man(ld).
man(lm).
man(nd).
man(ngan).
man(nguyen).
man(nm).
man(td).
man(thao).
man(tm).
man_jack(an).
man_jack(ld).
man_jack(lm).
man_jack(nd).
man_jack(ngan).
man_jack(nguyen).
man_jack(nm).
man_jack(td).
man_jack(thao).
man_jack(tm).
manipulator(an).
manipulator(ld).
manipulator(lm).
manipulator(nd).
manipulator(ngan).
manipulator(nguyen).
manipulator(nm).
manipulator(td).
manipulator(thao).
manipulator(tm).
married(an).
married(ld).
married(lm).
married(nd).
married(ngan).
married(nguyen).
married(nm).
married(td).
married(thao).
married(tm).
masturbator(an).
masturbator(ld).
masturbator(lm).
masturbator(nd).
masturbator(ngan).
masturbator(nguyen).
masturbator(nm).
masturbator(td).
masturbator(thao).
masturbator(tm).
mate(ngan, nguyen).
mate(ngan, thao).
mate(nguyen, ngan).
mate(nguyen, thao).
mate(thao, ngan).
mate(thao, nguyen).
measurer(an).
measurer(ld).
measurer(lm).
measurer(nd).
measurer(ngan).
measurer(nguyen).
measurer(nm).
measurer(td).
measurer(thao).
measurer(tm).
medical_student(ngan).
medical_student(nguyen).
medical_student(thao).
mesomorph(an).
mesomorph(ld).
mesomorph(lm).
mesomorph(nd).
mesomorph(ngan).
mesomorph(nguyen).
mesomorph(nm).
mesomorph(td).
mesomorph(thao).
mesomorph(tm).
mestizo(an).
mestizo(ld).
mestizo(lm).
mestizo(nd).
mestizo(ngan).
mestizo(nguyen).
mestizo(nm).
mestizo(td).
mestizo(thao).
mestizo(tm).
metropolis(gl).
metropolis(vt).
middlebrow(an).
middlebrow(ld).
middlebrow(lm).
middlebrow(nd).
middlebrow(ngan).
middlebrow(nguyen).
middlebrow(nm).
middlebrow(td).
middlebrow(thao).
middlebrow(tm).
miracle_man(an).
miracle_man(ld).
miracle_man(lm).
miracle_man(nd).
miracle_man(ngan).
miracle_man(nguyen).
miracle_man(nm).
miracle_man(td).
miracle_man(thao).
miracle_man(tm).
misogamist(an).
misogamist(ld).
misogamist(lm).
misogamist(nd).
misogamist(ngan).
misogamist(nguyen).
misogamist(nm).
misogamist(td).
misogamist(thao).
misogamist(tm).
mixed_blood(an).
mixed_blood(ld).
mixed_blood(lm).
mixed_blood(nd).
mixed_blood(ngan).
mixed_blood(nguyen).
mixed_blood(nm).
mixed_blood(td).
mixed_blood(thao).
mixed_blood(tm).
modern(an).
modern(ld).
modern(lm).
modern(nd).
modern(ngan).
modern(nguyen).
modern(nm).
modern(td).
modern(thao).
modern(tm).
mom(lm).
mom(nm).
mom(tm).
momma(lm).
momma(nm).
momma(tm).
mommy(lm).
mommy(nm).
mommy(tm).
money_handler(an).
money_handler(ld).
money_handler(lm).
money_handler(nd).
money_handler(ngan).
money_handler(nguyen).
money_handler(nm).
money_handler(td).
money_handler(thao).
money_handler(tm).
monolingual(an).
monolingual(ld).
monolingual(lm).
monolingual(nd).
monolingual(ngan).
monolingual(nguyen).
monolingual(nm).
monolingual(td).
monolingual(thao).
monolingual(tm).
mortal(an).
mortal(ld).
mortal(lm).
mortal(nd).
mortal(ngan).
mortal(nguyen).
mortal(nm).
mortal(td).
mortal(thao).
mortal(tm).
mother(lm).
mother(nm).
mother(tm).
mother_hen(an).
mother_hen(ld).
mother_hen(lm).
mother_hen(nd).
mother_hen(ngan).
mother_hen(nguyen).
mother_hen(nm).
mother_hen(td).
mother_hen(thao).
mother_hen(tm).
mouse(an).
mouse(ld).
mouse(lm).
mouse(nd).
mouse(ngan).
mouse(nguyen).
mouse(nm).
mouse(td).
mouse(thao).
mouse(tm).
mum(lm).
mum(nm).
mum(tm).
mummy(lm).
mummy(nm).
mummy(tm).
municipality(gl).
municipality(vt).
mutilator(an).
mutilator(ld).
mutilator(lm).
mutilator(nd).
mutilator(ngan).
mutilator(nguyen).
mutilator(nm).
mutilator(td).
mutilator(thao).
mutilator(tm).
namer(an).
namer(ld).
namer(lm).
namer(nd).
namer(ngan).
namer(nguyen).
namer(nm).
namer(td).
namer(thao).
namer(tm).
namesake(an).
namesake(ld).
namesake(lm).
namesake(nd).
namesake(ngan).
namesake(nguyen).
namesake(nm).
namesake(td).
namesake(thao).
namesake(tm).
national(an).
national(ld).
national(lm).
national(nd).
national(ngan).
national(nguyen).
national(nm).
national(td).
national(thao).
national(tm).
national_capital(gl).
national_capital(vt).
native(an).
native(ld).
native(lm).
native(nd).
native(ngan).
native(nguyen).
native(nm).
native(td).
native(thao).
native(tm).
neglecter(an).
neglecter(ld).
neglecter(lm).
neglecter(nd).
neglecter(ngan).
neglecter(nguyen).
neglecter(nm).
neglecter(td).
neglecter(thao).
neglecter(tm).
neighbor(an).
neighbor(ld).
neighbor(lm).
neighbor(nd).
neighbor(ngan).
neighbor(nguyen).
neighbor(nm).
neighbor(td).
neighbor(thao).
neighbor(tm).
neutral(an).
neutral(ld).
neutral(lm).
neutral(nd).
neutral(ngan).
neutral(nguyen).
neutral(nm).
neutral(td).
neutral(thao).
neutral(tm).
nondescript(an).
nondescript(ld).
nondescript(lm).
nondescript(nd).
nondescript(ngan).
nondescript(nguyen).
nondescript(nm).
nondescript(td).
nondescript(thao).
nondescript(tm).
nonmember(an).
nonmember(ld).
nonmember(lm).
nonmember(nd).
nonmember(ngan).
nonmember(nguyen).
nonmember(nm).
nonmember(td).
nonmember(thao).
nonmember(tm).
nonparticipant(an).
nonparticipant(ld).
nonparticipant(lm).
nonparticipant(nd).
nonparticipant(ngan).
nonparticipant(nguyen).
nonparticipant(nm).
nonparticipant(td).
nonparticipant(thao).
nonparticipant(tm).
nonpartisan(an).
nonpartisan(ld).
nonpartisan(lm).
nonpartisan(nd).
nonpartisan(ngan).
nonpartisan(nguyen).
nonpartisan(nm).
nonpartisan(td).
nonpartisan(thao).
nonpartisan(tm).
nonperson(an).
nonperson(ld).
nonperson(lm).
nonperson(nd).
nonperson(ngan).
nonperson(nguyen).
nonperson(nm).
nonperson(td).
nonperson(thao).
nonperson(tm).
nonreader(ngan).
nonreader(nguyen).
nonreader(thao).
nonreligious_person(an).
nonreligious_person(ld).
nonreligious_person(lm).
nonreligious_person(nd).
nonreligious_person(ngan).
nonreligious_person(nguyen).
nonreligious_person(nm).
nonreligious_person(td).
nonreligious_person(thao).
nonreligious_person(tm).
nonresident(an).
nonresident(ld).
nonresident(lm).
nonresident(nd).
nonresident(ngan).
nonresident(nguyen).
nonresident(nm).
nonresident(td).
nonresident(thao).
nonresident(tm).
nonsmoker(an).
nonsmoker(ld).
nonsmoker(lm).
nonsmoker(nd).
nonsmoker(ngan).
nonsmoker(nguyen).
nonsmoker(nm).
nonsmoker(td).
nonsmoker(thao).
nonsmoker(tm).
nonworker(an).
nonworker(ld).
nonworker(lm).
nonworker(nd).
nonworker(ngan).
nonworker(nguyen).
nonworker(nm).
nonworker(td).
nonworker(thao).
nonworker(tm).
nude(an).
nude(ld).
nude(lm).
nude(nd).
nude(ngan).
nude(nguyen).
nude(nm).
nude(td).
nude(thao).
nude(tm).
nurser(an).
nurser(ld).
nurser(lm).
nurser(nd).
nurser(ngan).
nurser(nguyen).
nurser(nm).
nurser(td).
nurser(thao).
nurser(tm).
occultist(an).
occultist(ld).
occultist(lm).
occultist(nd).
occultist(ngan).
occultist(nguyen).
occultist(nm).
occultist(td).
occultist(thao).
occultist(tm).
optimist(an).
optimist(ld).
optimist(lm).
optimist(nd).
optimist(ngan).
optimist(nguyen).
optimist(nm).
optimist(td).
optimist(thao).
optimist(tm).
organism(an).
organism(ld).
organism(lm).
organism(nd).
organism(ngan).
organism(nguyen).
organism(nm).
organism(td).
organism(thao).
organism(tm).
orphan(an).
orphan(ld).
orphan(lm).
orphan(nd).
orphan(ngan).
orphan(nguyen).
orphan(nm).
orphan(td).
orphan(thao).
orphan(tm).
ostrich(an).
ostrich(ld).
ostrich(lm).
ostrich(nd).
ostrich(ngan).
ostrich(nguyen).
ostrich(nm).
ostrich(td).
ostrich(thao).
ostrich(tm).
ouster(an).
ouster(ld).
ouster(lm).
ouster(nd).
ouster(ngan).
ouster(nguyen).
ouster(nm).
ouster(td).
ouster(thao).
ouster(tm).
outcaste(an).
outcaste(ld).
outcaste(lm).
outcaste(nd).
outcaste(ngan).
outcaste(nguyen).
outcaste(nm).
outcaste(td).
outcaste(thao).
outcaste(tm).
outdoorsman(an).
outdoorsman(ld).
outdoorsman(lm).
outdoorsman(nd).
outdoorsman(ngan).
outdoorsman(nguyen).
outdoorsman(nm).
outdoorsman(td).
outdoorsman(thao).
outdoorsman(tm).
overachiever(ngan).
overachiever(nguyen).
overachiever(thao).
owner(an).
owner(ld).
owner(lm).
owner(nd).
owner(ngan).
owner(nguyen).
owner(nm).
owner(td).
owner(thao).
owner(tm).
pa(ld).
pa(nd).
pa(td).
pamperer(an).
pamperer(ld).
pamperer(lm).
pamperer(nd).
pamperer(ngan).
pamperer(nguyen).
pamperer(nm).
pamperer(td).
pamperer(thao).
pamperer(tm).
pansexual(an).
pansexual(ld).
pansexual(lm).
pansexual(nd).
pansexual(ngan).
pansexual(nguyen).
pansexual(nm).
pansexual(td).
pansexual(thao).
pansexual(tm).
papa(ld).
papa(nd).
papa(td).
pappa(ld).
pappa(nd).
pappa(td).
pardoner(an).
pardoner(ld).
pardoner(lm).
pardoner(nd).
pardoner(ngan).
pardoner(nguyen).
pardoner(nm).
pardoner(td).
pardoner(thao).
pardoner(tm).
partner(an).
partner(ld).
partner(lm).
partner(nd).
partner(ngan).
partner(nguyen).
partner(nm).
partner(td).
partner(thao).
partner(tm).
party(an).
party(ld).
party(lm).
party(nd).
party(ngan).
party(nguyen).
party(nm).
party(td).
party(thao).
party(tm).
passer(an).
passer(ld).
passer(lm).
passer(nd).
passer(ngan).
passer(nguyen).
passer(nm).
passer(td).
passer(thao).
passer(tm).
peer(an).
peer(ld).
peer(lm).
peer(nd).
peer(ngan).
peer(nguyen).
peer(nm).
peer(td).
peer(thao).
peer(tm).
perceiver(an).
perceiver(ld).
perceiver(lm).
perceiver(nd).
perceiver(ngan).
perceiver(nguyen).
perceiver(nm).
perceiver(td).
perceiver(thao).
perceiver(tm).
percher(an).
percher(ld).
percher(lm).
percher(nd).
percher(ngan).
percher(nguyen).
percher(nm).
percher(td).
percher(thao).
percher(tm).
person(an).
person(ld).
person(lm).
person(nd).
person(ngan).
person(nguyen).
person(nm).
person(td).
person(thao).
person(tm).
person_of_color(an).
person_of_color(ld).
person_of_color(lm).
person_of_color(nd).
person_of_color(ngan).
person_of_color(nguyen).
person_of_color(nm).
person_of_color(td).
person_of_color(thao).
person_of_color(tm).
personage(an).
personage(ld).
personage(lm).
personage(nd).
personage(ngan).
personage(nguyen).
personage(nm).
personage(td).
personage(thao).
personage(tm).
personification(an).
personification(ld).
personification(lm).
personification(nd).
personification(ngan).
personification(nguyen).
personification(nm).
personification(td).
personification(thao).
personification(tm).
perspirer(an).
perspirer(ld).
perspirer(lm).
perspirer(nd).
perspirer(ngan).
perspirer(nguyen).
perspirer(nm).
perspirer(td).
perspirer(thao).
perspirer(tm).
philosopher(an).
philosopher(ld).
philosopher(lm).
philosopher(nd).
philosopher(ngan).
philosopher(nguyen).
philosopher(nm).
philosopher(td).
philosopher(thao).
philosopher(tm).
picker(an).
picker(ld).
picker(lm).
picker(nd).
picker(ngan).
picker(nguyen).
picker(nm).
picker(td).
picker(thao).
picker(tm).
pisces(an).
pisces(ld).
pisces(lm).
pisces(nd).
pisces(ngan).
pisces(nguyen).
pisces(nm).
pisces(td).
pisces(thao).
pisces(tm).
pisser(an).
pisser(ld).
pisser(lm).
pisser(nd).
pisser(ngan).
pisser(nguyen).
pisser(nm).
pisser(td).
pisser(thao).
pisser(tm).
plage(bh).
planner(an).
planner(ld).
planner(lm).
planner(nd).
planner(ngan).
planner(nguyen).
planner(nm).
planner(td).
planner(thao).
planner(tm).
planter(ld).
planter(lm).
player(an).
player(ld).
player(lm).
player(nd).
player(ngan).
player(nguyen).
player(nm).
player(td).
player(thao).
player(tm).
pop(ld).
pop(nd).
pop(td).
posturer(an).
posturer(ld).
posturer(lm).
posturer(nd).
posturer(ngan).
posturer(nguyen).
posturer(nm).
posturer(td).
posturer(thao).
posturer(tm).
powderer(an).
powderer(ld).
powderer(lm).
powderer(nd).
powderer(ngan).
powderer(nguyen).
powderer(nm).
powderer(td).
powderer(thao).
powderer(tm).
precursor(an).
precursor(ld).
precursor(lm).
precursor(nd).
precursor(ngan).
precursor(nguyen).
precursor(nm).
precursor(td).
precursor(thao).
precursor(tm).
preserver(an).
preserver(ld).
preserver(lm).
preserver(nd).
preserver(ngan).
preserver(nguyen).
preserver(nm).
preserver(td).
preserver(thao).
preserver(tm).
primitive(an).
primitive(ld).
primitive(lm).
primitive(nd).
primitive(ngan).
primitive(nguyen).
primitive(nm).
primitive(td).
primitive(thao).
primitive(tm).
profuse(gl).
propositus(an).
propositus(ld).
propositus(lm).
propositus(nd).
propositus(ngan).
propositus(nguyen).
propositus(nm).
propositus(td).
propositus(thao).
propositus(tm).
provincial_capital(gl).
provincial_capital(vt).
public_relations_person(an).
public_relations_person(ld).
public_relations_person(lm).
public_relations_person(nd).
public_relations_person(ngan).
public_relations_person(nguyen).
public_relations_person(nm).
public_relations_person(td).
public_relations_person(thao).
public_relations_person(tm).
pupil(ngan).
pupil(nguyen).
pupil(thao).
pursuer(an).
pursuer(ld).
pursuer(lm).
pursuer(nd).
pursuer(ngan).
pursuer(nguyen).
pursuer(nm).
pursuer(td).
pursuer(thao).
pursuer(tm).
pussycat(an).
pussycat(ld).
pussycat(lm).
pussycat(nd).
pussycat(ngan).
pussycat(nguyen).
pussycat(nm).
pussycat(td).
pussycat(thao).
pussycat(tm).
quarter(an).
quarter(ld).
quarter(lm).
quarter(nd).
quarter(ngan).
quarter(nguyen).
quarter(nm).
quarter(td).
quarter(thao).
quarter(tm).
quitter(an).
quitter(ld).
quitter(lm).
quitter(nd).
quitter(ngan).
quitter(nguyen).
quitter(nm).
quitter(td).
quitter(thao).
quitter(tm).
radical(an).
radical(ld).
radical(lm).
radical(nd).
radical(ngan).
radical(nguyen).
radical(nm).
radical(td).
radical(thao).
radical(tm).
rancher(ld).
rancher(lm).
realist(an).
realist(ld).
realist(lm).
realist(nd).
realist(ngan).
realist(nguyen).
realist(nm).
realist(td).
realist(thao).
realist(tm).
rectifier(an).
rectifier(ld).
rectifier(lm).
rectifier(nd).
rectifier(ngan).
rectifier(nguyen).
rectifier(nm).
rectifier(td).
rectifier(thao).
rectifier(tm).
redhead(an).
redhead(ld).
redhead(lm).
redhead(nd).
redhead(ngan).
redhead(nguyen).
redhead(nm).
redhead(td).
redhead(thao).
redhead(tm).
refreshful(bh).
refreshing(bh).
registrant(an).
registrant(ld).
registrant(lm).
registrant(nd).
registrant(ngan).
registrant(nguyen).
registrant(nm).
registrant(td).
registrant(thao).
registrant(tm).
relative(an).
relative(ld).
relative(lm).
relative(nd).
relative(ngan).
relative(nguyen).
relative(nm).
relative(td).
relative(thao).
relative(tm).
reliever(an).
reliever(ld).
reliever(lm).
reliever(nd).
reliever(ngan).
reliever(nguyen).
reliever(nm).
reliever(td).
reliever(thao).
reliever(tm).
religious_person(an).
religious_person(ld).
religious_person(lm).
religious_person(nd).
religious_person(ngan).
religious_person(nguyen).
religious_person(nm).
religious_person(td).
religious_person(thao).
religious_person(tm).
repeater(an).
repeater(ld).
repeater(lm).
repeater(nd).
repeater(ngan).
repeater(nguyen).
repeater(nm).
repeater(td).
repeater(thao).
repeater(tm).
rescuer(an).
rescuer(ld).
rescuer(lm).
rescuer(nd).
rescuer(ngan).
rescuer(nguyen).
rescuer(nm).
rescuer(td).
rescuer(thao).
rescuer(tm).
rester(an).
rester(ld).
rester(lm).
rester(nd).
rester(ngan).
rester(nguyen).
rester(nm).
rester(td).
rester(thao).
rester(tm).
restrainer(an).
restrainer(ld).
restrainer(lm).
restrainer(nd).
restrainer(ngan).
restrainer(nguyen).
restrainer(nm).
restrainer(td).
restrainer(thao).
restrainer(tm).
revenant(an).
revenant(ld).
revenant(lm).
revenant(nd).
revenant(ngan).
revenant(nguyen).
revenant(nm).
revenant(td).
revenant(thao).
revenant(tm).
rich_person(an).
rich_person(ld).
rich_person(lm).
rich_person(nd).
rich_person(ngan).
rich_person(nguyen).
rich_person(nm).
rich_person(td).
rich_person(thao).
rich_person(tm).
right_hander(an).
right_hander(ld).
right_hander(lm).
right_hander(nd).
right_hander(ngan).
right_hander(nguyen).
right_hander(nm).
right_hander(td).
right_hander(thao).
right_hander(tm).
riotous(gl).
riser(an).
riser(ld).
riser(lm).
riser(nd).
riser(ngan).
riser(nguyen).
riser(nm).
riser(td).
riser(thao).
riser(tm).
role(X, student) :- student(X).
romper(an).
romper(ld).
romper(lm).
romper(nd).
romper(ngan).
romper(nguyen).
romper(nm).
romper(td).
romper(thao).
romper(tm).
roommate(ngan, nguyen).
roommate(ngan, thao).
roommate(nguyen, ngan).
roommate(nguyen, thao).
roommate(thao, ngan).
roommate(thao, nguyen).
roundhead(an).
roundhead(ld).
roundhead(lm).
roundhead(nd).
roundhead(ngan).
roundhead(nguyen).
roundhead(nm).
roundhead(td).
roundhead(thao).
roundhead(tm).
ruler(an).
ruler(ld).
ruler(lm).
ruler(nd).
ruler(ngan).
ruler(nguyen).
ruler(nm).
ruler(td).
ruler(thao).
ruler(tm).
rusher(an).
rusher(ld).
rusher(lm).
rusher(nd).
rusher(ngan).
rusher(nguyen).
rusher(nm).
rusher(td).
rusher(thao).
rusher(tm).
s(ngan, nd).
s(ngan, nm).
s(nguyen, ld).
s(nguyen, lm).
s(thao, td).
s(thao, tm).
sagittarius(an).
sagittarius(ld).
sagittarius(lm).
sagittarius(nd).
sagittarius(ngan).
sagittarius(nguyen).
sagittarius(nm).
sagittarius(td).
sagittarius(thao).
sagittarius(tm).
scholar(ngan).
scholar(nguyen).
scholar(thao).
schoolfriend(ngan, nguyen).
schoolfriend(ngan, thao).
schoolfriend(nguyen, ngan).
schoolfriend(nguyen, thao).
schoolfriend(thao, ngan).
schoolfriend(thao, nguyen).
scientist(an).
scientist(ld).
scientist(lm).
scientist(nd).
scientist(ngan).
scientist(nguyen).
scientist(nm).
scientist(td).
scientist(thao).
scientist(tm).
scorpio(an).
scorpio(ld).
scorpio(lm).
scorpio(nd).
scorpio(ngan).
scorpio(nguyen).
scorpio(nm).
scorpio(td).
scorpio(thao).
scorpio(tm).
scratcher(an).
scratcher(ld).
scratcher(lm).
scratcher(nd).
scratcher(ngan).
scratcher(nguyen).
scratcher(nm).
scratcher(td).
scratcher(thao).
scratcher(tm).
second_rater(an).
second_rater(ld).
second_rater(lm).
second_rater(nd).
second_rater(ngan).
second_rater(nguyen).
second_rater(nm).
second_rater(td).
second_rater(thao).
second_rater(tm).
seeder(an).
seeder(ld).
seeder(lm).
seeder(nd).
seeder(ngan).
seeder(nguyen).
seeder(nm).
seeder(td).
seeder(thao).
seeder(tm).
seeker(an).
seeker(ld).
seeker(lm).
seeker(nd).
seeker(ngan).
seeker(nguyen).
seeker(nm).
seeker(td).
seeker(thao).
seeker(tm).
segregate(an).
segregate(ld).
segregate(lm).
segregate(nd).
segregate(ngan).
segregate(nguyen).
segregate(nm).
segregate(td).
segregate(thao).
segregate(tm).
self(an).
self(ld).
self(lm).
self(nd).
self(ngan).
self(nguyen).
self(nm).
self(td).
self(thao).
self(tm).
seminarian(ngan).
seminarian(nguyen).
seminarian(thao).
sensualist(an).
sensualist(ld).
sensualist(lm).
sensualist(nd).
sensualist(ngan).
sensualist(nguyen).
sensualist(nm).
sensualist(td).
sensualist(thao).
sensualist(tm).
sentimentalist(an).
sentimentalist(ld).
sentimentalist(lm).
sentimentalist(nd).
sentimentalist(ngan).
sentimentalist(nguyen).
sentimentalist(nm).
sentimentalist(td).
sentimentalist(thao).
sentimentalist(tm).
sex_object(an).
sex_object(ld).
sex_object(lm).
sex_object(nd).
sex_object(ngan).
sex_object(nguyen).
sex_object(nm).
sex_object(td).
sex_object(thao).
sex_object(tm).
sex_symbol(an).
sex_symbol(ld).
sex_symbol(lm).
sex_symbol(nd).
sex_symbol(ngan).
sex_symbol(nguyen).
sex_symbol(nm).
sex_symbol(td).
sex_symbol(thao).
sex_symbol(tm).
shaker(an).
shaker(ld).
shaker(lm).
shaker(nd).
shaker(ngan).
shaker(nguyen).
shaker(nm).
shaker(td).
shaker(thao).
shaker(tm).
showman(an).
showman(ld).
showman(lm).
showman(nd).
showman(ngan).
showman(nguyen).
showman(nm).
showman(td).
showman(thao).
showman(tm).
signer(an).
signer(ld).
signer(lm).
signer(nd).
signer(ngan).
signer(nguyen).
signer(nm).
signer(td).
signer(thao).
signer(tm).
simpleton(an).
simpleton(ld).
simpleton(lm).
simpleton(nd).
simpleton(ngan).
simpleton(nguyen).
simpleton(nm).
simpleton(td).
simpleton(thao).
simpleton(tm).
six_footer(an).
six_footer(ld).
six_footer(lm).
six_footer(nd).
six_footer(ngan).
six_footer(nguyen).
six_footer(nm).
six_footer(td).
six_footer(thao).
six_footer(tm).
sixth_former(ngan).
sixth_former(nguyen).
sixth_former(thao).
skidder(an).
skidder(ld).
skidder(lm).
skidder(nd).
skidder(ngan).
skidder(nguyen).
skidder(nm).
skidder(td).
skidder(thao).
skidder(tm).
skilled_worker(td).
skipper(ngan).
skipper(nguyen).
skipper(thao).
slav(an).
slav(ld).
slav(lm).
slav(nd).
slav(ngan).
slav(nguyen).
slav(nm).
slav(td).
slav(thao).
slav(tm).
slave(an).
slave(ld).
slave(lm).
slave(nd).
slave(ngan).
slave(nguyen).
slave(nm).
slave(td).
slave(thao).
slave(tm).
sleepyhead(an).
sleepyhead(ld).
sleepyhead(lm).
sleepyhead(nd).
sleepyhead(ngan).
sleepyhead(nguyen).
sleepyhead(nm).
sleepyhead(td).
sleepyhead(thao).
sleepyhead(tm).
sloucher(an).
sloucher(ld).
sloucher(lm).
sloucher(nd).
sloucher(ngan).
sloucher(nguyen).
sloucher(nm).
sloucher(td).
sloucher(thao).
sloucher(tm).
small_farmer(ld).
small_farmer(lm).
small_person(an).
small_person(ld).
small_person(lm).
small_person(nd).
small_person(ngan).
small_person(nguyen).
small_person(nm).
small_person(td).
small_person(thao).
small_person(tm).
smallholder(ld).
smallholder(lm).
smasher(an).
smasher(ld).
smasher(lm).
smasher(nd).
smasher(ngan).
smasher(nguyen).
smasher(nm).
smasher(td).
smasher(thao).
smasher(tm).
smiler(an).
smiler(ld).
smiler(lm).
smiler(nd).
smiler(ngan).
smiler(nguyen).
smiler(nm).
smiler(td).
smiler(thao).
smiler(tm).
sneezer(an).
sneezer(ld).
sneezer(lm).
sneezer(nd).
sneezer(ngan).
sneezer(nguyen).
sneezer(nm).
sneezer(td).
sneezer(thao).
sneezer(tm).
sniffer(an).
sniffer(ld).
sniffer(lm).
sniffer(nd).
sniffer(ngan).
sniffer(nguyen).
sniffer(nm).
sniffer(td).
sniffer(thao).
sniffer(tm).
sniffler(an).
sniffler(ld).
sniffler(lm).
sniffler(nd).
sniffler(ngan).
sniffler(nguyen).
sniffler(nm).
sniffler(td).
sniffler(thao).
sniffler(tm).
snuffer(an).
snuffer(ld).
snuffer(lm).
snuffer(nd).
snuffer(ngan).
snuffer(nguyen).
snuffer(nm).
snuffer(td).
snuffer(thao).
snuffer(tm).
snuffler(an).
snuffler(ld).
snuffler(lm).
snuffler(nd).
snuffler(ngan).
snuffler(nguyen).
snuffler(nm).
snuffler(td).
snuffler(thao).
snuffler(tm).
socializer(an).
socializer(ld).
socializer(lm).
socializer(nd).
socializer(ngan).
socializer(nguyen).
socializer(nm).
socializer(td).
socializer(thao).
socializer(tm).
sodbuster(ld).
sodbuster(lm).
somebody(an).
somebody(ld).
somebody(lm).
somebody(nd).
somebody(ngan).
somebody(nguyen).
somebody(nm).
somebody(td).
somebody(thao).
somebody(tm).
someone(an).
someone(ld).
someone(lm).
someone(nd).
someone(ngan).
someone(nguyen).
someone(nm).
someone(td).
someone(thao).
someone(tm).
sort(an).
sort(ld).
sort(lm).
sort(nd).
sort(ngan).
sort(nguyen).
sort(nm).
sort(td).
sort(thao).
sort(tm).
soul(an).
soul(ld).
soul(lm).
soul(nd).
soul(ngan).
soul(nguyen).
soul(nm).
soul(td).
soul(thao).
soul(tm).
sounding_board(an).
sounding_board(ld).
sounding_board(lm).
sounding_board(nd).
sounding_board(ngan).
sounding_board(nguyen).
sounding_board(nm).
sounding_board(td).
sounding_board(thao).
sounding_board(tm).
sower(ld).
sower(lm).
sphinx(an).
sphinx(ld).
sphinx(lm).
sphinx(nd).
sphinx(ngan).
sphinx(nguyen).
sphinx(nm).
sphinx(td).
sphinx(thao).
sphinx(tm).
spitter(an).
spitter(ld).
spitter(lm).
spitter(nd).
spitter(ngan).
spitter(nguyen).
spitter(nm).
spitter(td).
spitter(thao).
spitter(tm).
sport(an).
sport(ld).
sport(lm).
sport(nd).
sport(ngan).
sport(nguyen).
sport(nm).
sport(td).
sport(thao).
sport(tm).
sprawler(an).
sprawler(ld).
sprawler(lm).
sprawler(nd).
sprawler(ngan).
sprawler(nguyen).
sprawler(nm).
sprawler(td).
sprawler(thao).
sprawler(tm).
spurner(an).
spurner(ld).
spurner(lm).
spurner(nd).
spurner(ngan).
spurner(nguyen).
spurner(nm).
spurner(td).
spurner(thao).
spurner(tm).
squinter(an).
squinter(ld).
squinter(lm).
squinter(nd).
squinter(ngan).
squinter(nguyen).
squinter(nm).
squinter(td).
squinter(thao).
squinter(tm).
state_capital(gl).
state_capital(vt).
stifler(an).
stifler(ld).
stifler(lm).
stifler(nd).
stifler(ngan).
stifler(nguyen).
stifler(nm).
stifler(td).
stifler(thao).
stifler(tm).
stigmatic(an).
stigmatic(ld).
stigmatic(lm).
stigmatic(nd).
stigmatic(ngan).
stigmatic(nguyen).
stigmatic(nm).
stigmatic(td).
stigmatic(thao).
stigmatic(tm).
stockman(ld).
stockman(lm).
stooper(an).
stooper(ld).
stooper(lm).
stooper(nd).
stooper(ngan).
stooper(nguyen).
stooper(nm).
stooper(td).
stooper(thao).
stooper(tm).
stranger(an).
stranger(ld).
stranger(lm).
stranger(nd).
stranger(ngan).
stranger(nguyen).
stranger(nm).
stranger(td).
stranger(thao).
stranger(tm).
struggler(an).
struggler(ld).
struggler(lm).
struggler(nd).
struggler(ngan).
struggler(nguyen).
struggler(nm).
struggler(td).
struggler(thao).
struggler(tm).
student(ngan).
student(nguyen).
student(thao).
subject(an).
subject(ld).
subject(lm).
subject(nd).
subject(ngan).
subject(nguyen).
subject(nm).
subject(td).
subject(thao).
subject(tm).
supernumerary(an).
supernumerary(ld).
supernumerary(lm).
supernumerary(nd).
supernumerary(ngan).
supernumerary(nguyen).
supernumerary(nm).
supernumerary(td).
supernumerary(thao).
supernumerary(tm).
surrenderer(an).
surrenderer(ld).
surrenderer(lm).
surrenderer(nd).
surrenderer(ngan).
surrenderer(nguyen).
surrenderer(nm).
surrenderer(td).
surrenderer(thao).
surrenderer(tm).
survivalist(an).
survivalist(ld).
survivalist(lm).
survivalist(nd).
survivalist(ngan).
survivalist(nguyen).
survivalist(nm).
survivalist(td).
survivalist(thao).
survivalist(tm).
survivor(an).
survivor(ld).
survivor(lm).
survivor(nd).
survivor(ngan).
survivor(nguyen).
survivor(nm).
survivor(td).
survivor(thao).
survivor(tm).
suspect(an).
suspect(ld).
suspect(lm).
suspect(nd).
suspect(ngan).
suspect(nguyen).
suspect(nm).
suspect(td).
suspect(thao).
suspect(tm).
tagger(an).
tagger(ld).
tagger(lm).
tagger(nd).
tagger(ngan).
tagger(nguyen).
tagger(nm).
tagger(td).
tagger(thao).
tagger(tm).
tapper(an).
tapper(ld).
tapper(lm).
tapper(nd).
tapper(ngan).
tapper(nguyen).
tapper(nm).
tapper(td).
tapper(thao).
tapper(tm).
taurus(an).
taurus(ld).
taurus(lm).
taurus(nd).
taurus(ngan).
taurus(nguyen).
taurus(nm).
taurus(td).
taurus(thao).
taurus(tm).
tempter(an).
tempter(ld).
tempter(lm).
tempter(nd).
tempter(ngan).
tempter(nguyen).
tempter(nm).
tempter(td).
tempter(thao).
tempter(tm).
tenant_farmer(ld).
tenant_farmer(lm).
termer(an).
termer(ld).
termer(lm).
termer(nd).
termer(ngan).
termer(nguyen).
termer(nm).
termer(td).
termer(thao).
termer(tm).
terror(an).
terror(ld).
terror(lm).
terror(nd).
terror(ngan).
terror(nguyen).
terror(nm).
terror(td).
terror(thao).
terror(tm).
testator(an).
testator(ld).
testator(lm).
testator(nd).
testator(ngan).
testator(nguyen).
testator(nm).
testator(td).
testator(thao).
testator(tm).
thin_person(an).
thin_person(ld).
thin_person(lm).
thin_person(nd).
thin_person(ngan).
thin_person(nguyen).
thin_person(nm).
thin_person(td).
thin_person(thao).
thin_person(tm).
third_rater(an).
third_rater(ld).
third_rater(lm).
third_rater(nd).
third_rater(ngan).
third_rater(nguyen).
third_rater(nm).
third_rater(td).
third_rater(thao).
third_rater(tm).
thrower(an).
thrower(ld).
thrower(lm).
thrower(nd).
thrower(ngan).
thrower(nguyen).
thrower(nm).
thrower(td).
thrower(thao).
thrower(tm).
tiger(an).
tiger(ld).
tiger(lm).
tiger(nd).
tiger(ngan).
tiger(nguyen).
tiger(nm).
tiger(td).
tiger(thao).
tiger(tm).
tiller(ld).
tiller(lm).
tonic(bh).
totemist(an).
totemist(ld).
totemist(lm).
totemist(nd).
totemist(ngan).
totemist(nguyen).
totemist(nm).
totemist(td).
totemist(thao).
totemist(tm).
toucher(an).
toucher(ld).
toucher(lm).
toucher(nd).
toucher(ngan).
toucher(nguyen).
toucher(nm).
toucher(td).
toucher(thao).
toucher(tm).
town(ngan, vt).
town(nguyen, gl).
town(thao, vt).
trader(nd).
trader(nm).
transfer(an).
transfer(ld).
transfer(lm).
transfer(nd).
transfer(ngan).
transfer(nguyen).
transfer(nm).
transfer(td).
transfer(thao).
transfer(tm).
transsexual(an).
transsexual(ld).
transsexual(lm).
transsexual(nd).
transsexual(ngan).
transsexual(nguyen).
transsexual(nm).
transsexual(td).
transsexual(thao).
transsexual(tm).
transvestite(an).
transvestite(ld).
transvestite(lm).
transvestite(nd).
transvestite(ngan).
transvestite(nguyen).
transvestite(nm).
transvestite(td).
transvestite(thao).
transvestite(tm).
traveler(an).
traveler(ld).
traveler(lm).
traveler(nd).
traveler(ngan).
traveler(nguyen).
traveler(nm).
traveler(td).
traveler(thao).
traveler(tm).
trawler(td).
trier(an).
trier(ld).
trier(lm).
trier(nd).
trier(ngan).
trier(nguyen).
trier(nm).
trier(td).
trier(thao).
trier(tm).
turner(an).
turner(ld).
turner(lm).
turner(nd).
turner(ngan).
turner(nguyen).
turner(nm).
turner(td).
turner(thao).
turner(tm).
tyrant(an).
tyrant(ld).
tyrant(lm).
tyrant(nd).
tyrant(ngan).
tyrant(nguyen).
tyrant(nm).
tyrant(td).
tyrant(thao).
tyrant(tm).
underachiever(ngan).
underachiever(nguyen).
underachiever(thao).
undoer(an).
undoer(ld).
undoer(lm).
undoer(nd).
undoer(ngan).
undoer(nguyen).
undoer(nm).
undoer(td).
undoer(thao).
undoer(tm).
unfortunate(an).
unfortunate(ld).
unfortunate(lm).
unfortunate(nd).
unfortunate(ngan).
unfortunate(nguyen).
unfortunate(nm).
unfortunate(td).
unfortunate(thao).
unfortunate(tm).
unskilled_person(an).
unskilled_person(ld).
unskilled_person(lm).
unskilled_person(nd).
unskilled_person(ngan).
unskilled_person(nguyen).
unskilled_person(nm).
unskilled_person(td).
unskilled_person(thao).
unskilled_person(tm).
unwelcome_person(an).
unwelcome_person(ld).
unwelcome_person(lm).
unwelcome_person(nd).
unwelcome_person(ngan).
unwelcome_person(nguyen).
unwelcome_person(nm).
unwelcome_person(td).
unwelcome_person(thao).
unwelcome_person(tm).
urban_center(gl).
urban_center(vt).
user(an).
user(ld).
user(lm).
user(nd).
user(ngan).
user(nguyen).
user(nm).
user(td).
user(thao).
user(tm).
vanisher(an).
vanisher(ld).
vanisher(lm).
vanisher(nd).
vanisher(ngan).
vanisher(nguyen).
vanisher(nm).
vanisher(td).
vanisher(thao).
vanisher(tm).
victim(an).
victim(ld).
victim(lm).
victim(nd).
victim(ngan).
victim(nguyen).
victim(nm).
victim(td).
victim(thao).
victim(tm).
victorian(an).
victorian(ld).
victorian(lm).
victorian(nd).
victorian(ngan).
victorian(nguyen).
victorian(nm).
victorian(td).
victorian(thao).
victorian(tm).
virgo(an).
virgo(ld).
virgo(lm).
virgo(nd).
virgo(ngan).
virgo(nguyen).
virgo(nm).
virgo(td).
virgo(thao).
virgo(tm).
visionary(an).
visionary(ld).
visionary(lm).
visionary(nd).
visionary(ngan).
visionary(nguyen).
visionary(nm).
visionary(td).
visionary(thao).
visionary(tm).
visually_impaired_person(an).
visually_impaired_person(ld).
visually_impaired_person(lm).
visually_impaired_person(nd).
visually_impaired_person(ngan).
visually_impaired_person(nguyen).
visually_impaired_person(nm).
visually_impaired_person(td).
visually_impaired_person(thao).
visually_impaired_person(tm).
waiter(an).
waiter(ld).
waiter(lm).
waiter(nd).
waiter(ngan).
waiter(nguyen).
waiter(nm).
waiter(td).
waiter(thao).
waiter(tm).
waker(an).
waker(ld).
waker(lm).
waker(nd).
waker(ngan).
waker(nguyen).
waker(nm).
waker(td).
waker(thao).
waker(tm).
walk_in(an).
walk_in(ld).
walk_in(lm).
walk_in(nd).
walk_in(ngan).
walk_in(nguyen).
walk_in(nm).
walk_in(td).
walk_in(thao).
walk_in(tm).
wanter(an).
wanter(ld).
wanter(lm).
wanter(nd).
wanter(ngan).
wanter(nguyen).
wanter(nm).
wanter(td).
wanter(thao).
wanter(tm).
ward(an).
ward(ld).
ward(lm).
ward(nd).
ward(ngan).
ward(nguyen).
ward(nm).
ward(td).
ward(thao).
ward(tm).
warrior(an).
warrior(ld).
warrior(lm).
warrior(nd).
warrior(ngan).
warrior(nguyen).
warrior(nm).
warrior(td).
warrior(thao).
warrior(tm).
watcher(an).
watcher(ld).
watcher(lm).
watcher(nd).
watcher(ngan).
watcher(nguyen).
watcher(nm).
watcher(td).
watcher(thao).
watcher(tm).
weakling(an).
weakling(ld).
weakling(lm).
weakling(nd).
weakling(ngan).
weakling(nguyen).
weakling(nm).
weakling(td).
weakling(thao).
weakling(tm).
weasel(an).
weasel(ld).
weasel(lm).
weasel(nd).
weasel(ngan).
weasel(nguyen).
weasel(nm).
weasel(td).
weasel(thao).
weasel(tm).
white(an).
white(ld).
white(lm).
white(nd).
white(ngan).
white(nguyen).
white(nm).
white(td).
white(thao).
white(tm).
wife(tm).
wiggler(an).
wiggler(ld).
wiggler(lm).
wiggler(nd).
wiggler(ngan).
wiggler(nguyen).
wiggler(nm).
wiggler(td).
wiggler(thao).
wiggler(tm).
winker(an).
winker(ld).
winker(lm).
winker(nd).
winker(ngan).
winker(nguyen).
winker(nm).
winker(td).
winker(thao).
winker(tm).
withdrawer(ngan).
withdrawer(nguyen).
withdrawer(thao).
withholder(an).
withholder(ld).
withholder(lm).
withholder(nd).
withholder(ngan).
withholder(nguyen).
withholder(nm).
withholder(td).
withholder(thao).
withholder(tm).
witness(an).
witness(ld).
witness(lm).
witness(nd).
witness(ngan).
witness(nguyen).
witness(nm).
witness(td).
witness(thao).
witness(tm).
woman_of_the_house(tm).
worker(an).
worker(ld).
worker(lm).
worker(nd).
worker(ngan).
worker(nguyen).
worker(nm).
worker(td).
worker(thao).
worker(tm).
worldling(an).
worldling(ld).
worldling(lm).
worldling(nd).
worldling(ngan).
worldling(nguyen).
worldling(nm).
worldling(td).
worldling(thao).
worldling(tm).
wykehamist(ngan).
wykehamist(nguyen).
wykehamist(thao).
yawner(an).
yawner(ld).
yawner(lm).
yawner(nd).
yawner(ngan).
yawner(nguyen).
yawner(nm).
yawner(td).
yawner(thao).
yawner(tm).
